"""Renders the sudoers rule the console would need -- and never installs it.

The console has no code path that writes to /etc. Not one it declines to
take, not one behind a flag, not one behind a confirmation prompt: an install
mode that exists but goes unused is still an install mode someone will
eventually use. `render()` produces the file's text; `cmd_sudoers` in cli.py
writes it under packaging/, validates it with `visudo -c`, and hands the
operator the one command to run themselves.

A NOPASSWD rule is granted to a user account, not to this program. Once
installed, any process running as that account -- a script, a browser
extension, a compromised dependency -- can run the exact command below
without a password. Naming a login account here is a transitional state,
not the destination: the destination is a dedicated system user for the
service. That is why the rendered file carries the warning itself, in a
comment nobody has to go looking for a design document to find.

sudo-rs supports a subset of the classic sudoers grammar. This module stays
in the plainest possible form it accepts -- `user ALL=(root) NOPASSWD:
/absolute/path arg1 arg2` -- and uses no alias, no Defaults line, no
wildcard and never `ALL` as a command.
"""

from __future__ import annotations

from healthconsole.actions import CATALOGUE

HEADER = """\
# Generated by `health-console sudoers`. Do not hand-edit: regenerate it
# with that command and reinstall instead.
#
# TRANSITIONAL: the rule below names a login account, not a dedicated
# system user. A NOPASSWD rule is granted to that account, not to this
# program -- any process running as it (a script, a browser extension, a
# compromised dependency) can run the exact command below without a
# password. The destination is a dedicated system user for the service;
# naming a login account here is a stepping stone, not the design.
#
# Fixed arguments only, drawn from healthconsole/actions.py -- no
# wildcard, never ALL as a command.
"""


def render(user: str) -> str:
    """Build the sudoers file text for `user`.

    One NOPASSWD line per catalogue action with root=True, arguments
    included verbatim from `Action.argv`. Never a wildcard, never `ALL` as
    a command.
    """
    lines = [HEADER]
    for action in sorted(
            (a for a in CATALOGUE.values() if a.root), key=lambda a: a.id):
        command = " ".join(action.argv)
        lines.append(f"{user} ALL=(root) NOPASSWD: {command}")
    lines.append("")
    return "\n".join(lines)
