"""Renders the sudoers rule the console would need -- and never installs it.

The console has no code path that writes to /etc. Not one it declines to
take, not one behind a flag, not one behind a confirmation prompt: an install
mode that exists but goes unused is still an install mode someone will
eventually use. `render()` produces the file's text; `cmd_sudoers` in cli.py
writes it under packaging/, validates it with `visudo -c`, and hands the
operator the one command to run themselves.

A NOPASSWD rule is granted to a user account, not to this program. Once
installed, any process running as that account -- a script, a browser
extension, a compromised dependency -- can run the exact command below
without a password. Naming a login account here is a transitional state,
not the destination: the destination is a dedicated system user for the
service. That is why the rendered file carries the warning itself, in a
comment nobody has to go looking for a design document to find.

sudo-rs supports a subset of the classic sudoers grammar. This module stays
in the plainest possible form it accepts -- `user ALL=(root) NOPASSWD:
/absolute/path arg1 arg2` -- and uses no alias, no Defaults line, no
wildcard and never `ALL` as a command.

Both interpolated values are validated before a single line is built, and
`render()` raises rather than emit anything on a rejection:

- `user` must be a plain POSIX login name, and never the literal `ALL`.
  A username is not safe input just because it usually looks like one --
  `getpass.getuser()` (not called here; see cli.py, which resolves it from
  the password database instead) returns `$LOGNAME` / `$USER` verbatim,
  and a value such as ``prolice ALL=(ALL) NOPASSWD: ALL #`` parses
  cleanly under sudo-rs and replaces the intended rule with unrestricted
  root. The comment character swallows the rest of the line; without it,
  a bare ``ALL`` still grants every account on the machine while looking,
  at a glance, like a normal username. A name that is entirely uppercase
  and starts with a letter -- `ADMINS`, say -- is also rejected: that is
  the exact shape of a sudoers `User_Alias`, and a real account spelled
  that way would bind to the alias instead of the account in the user
  position of the rule.
- Every element of every root action's `argv` is validated against an
  **allowlist**, not a denylist. `CATALOGUE` is trusted data today, but
  this module renders whatever it is given, and a denylist of "characters
  sudoers treats specially" is a losing game: `#` opens a comment in
  sudo-rs 0.2.13 (proved against this machine's real `visudo` -- garbage
  after a bare command parses `rc=1`, the same garbage after `#` parses
  `rc=0 parsed OK`), an empty argument or a trailing `#` both degenerate
  the rule to a bare command name, which sudoers(5) documents as running
  "with any arguments they wish" -- root code execution through
  `apt-get`'s own option parsing -- and a Unicode zero-width space
  (U+200B) is invisible but is not matched by `\\s`. `argv[0]` must
  match one positive path shape -- one or more `/segment` groups, nothing
  before the first `/` and nothing after the last segment -- rather than
  a `startswith("/")` check plus a growing list of prohibitions: that
  shape alone rejects a bare `/`, a trailing `/` (sudoers-rs(5) treats a
  path ending in `/` as a *directory* spec, granting every file inside
  it -- reproduced end-to-end through `cmd_sudoers` with `visudo -c`
  reporting `parsed OK`), and it is checked alongside an explicit
  rejection of `.` or `..` as a whole path segment, applied to every
  argument, not only `argv[0]` -- `/usr/bin/./sh` and a later argument of
  `../etc/shadow` both still parsed clean without it. No element may be
  empty.
"""

from __future__ import annotations

import re

from healthconsole.actions import CATALOGUE

HEADER = """\
# Generated by `health-console sudoers`. Do not hand-edit: regenerate it
# with that command and reinstall instead.
#
# TRANSITIONAL: the rule below names a login account, not a dedicated
# system user. A NOPASSWD rule is granted to that account, not to this
# program -- any process running as it (a script, a browser extension, a
# compromised dependency) can run the exact command below without a
# password. The destination is a dedicated system user for the service;
# naming a login account here is a stepping stone, not the design.
#
# Fixed arguments only, drawn from healthconsole/actions.py -- no
# wildcard, never ALL as a command.
"""

# A plain POSIX login name: letters (either case -- POSIX allows both;
# case alone carries no meaning to sudoers), digits, underscore and
# hyphen, not starting with a digit or hyphen, at most 32 characters (the
# usual system limit). `ALL` would match this pattern -- it looks like an
# ordinary name -- which is exactly why it is rejected separately below
# rather than trusted to fall out of the character class.
_USER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_-]{0,31}")

# The shape of a sudoers User_Alias name: uppercase letters, digits and
# underscore, starting with an uppercase letter. A real account spelled
# this way -- ADMINS, say -- would bind to an alias of the same name
# instead of the account in the user position of the rule.
_ALIAS_LIKE_RE = re.compile(r"[A-Z][A-Z0-9_]*")

# argv[0]'s shape: an absolute path built of one or more "/segment"
# groups, nothing before the first "/" and nothing left over after the
# last segment. This is a positive shape, not "starts with / plus a
# growing list of prohibitions" -- that approach missed a trailing "/"
# (sudoers-rs(5): a path ending in "/" is a *directory* spec, granting
# every file inside it) and a bare "/" (every file on the filesystem).
_ARGV0_PATH_RE = re.compile(r"(?:/[A-Za-z0-9._-]+)+")

# What an argv element is allowed to contain -- an allowlist, not a
# denylist. sudo-rs's sudoers grammar reads far more as syntax than any
# enumerated denylist catches: `#` opens a comment (mid-token, not just at
# start of line), `:` separates fields, a bare or empty trailing element
# degenerates the whole rule to just the command name -- which sudoers(5)
# documents as letting the user run it "with any arguments they wish" --
# and a Unicode zero-width space is invisible to `\s`. Only what the real
# catalogue's commands and arguments need is let through.
_ARGV_SAFE_RE = re.compile(r"[A-Za-z0-9._/-]+")


def _validate_user(user: str) -> None:
    if user == "ALL" or not _USER_RE.fullmatch(user):
        raise ValueError(
            f"refusing to render a sudoers rule for {user!r}: not a plain "
            "POSIX login name")
    if _ALIAS_LIKE_RE.fullmatch(user):
        raise ValueError(
            f"refusing to render a sudoers rule for {user!r}: this is the "
            "shape of a sudoers User_Alias name and could bind to an "
            "alias instead of the account")


def _validate_argv(argv: tuple[str, ...]) -> None:
    if not argv:
        raise ValueError("refusing to render a sudoers rule: empty argv")
    if not _ARGV0_PATH_RE.fullmatch(argv[0]):
        raise ValueError(
            f"refusing to render a sudoers rule: argv[0] must be an "
            f"absolute file path -- no bare '/', no trailing '/' -- "
            f"got {argv!r}")
    for part in argv:
        if part == "" or not _ARGV_SAFE_RE.fullmatch(part):
            raise ValueError(
                f"refusing to render a sudoers rule: unsafe argument "
                f"{part!r} in {argv!r}")
        # '.' and '..' are within the allowed character set (a real
        # filename can contain either), so they are rejected as whole
        # path segments here rather than as characters, and for every
        # element -- not only argv[0] -- since a later argument
        # containing '/' is still a path as far as sudo-rs cares.
        if any(segment in (".", "..") for segment in part.split("/")):
            raise ValueError(
                f"refusing to render a sudoers rule: '.' or '..' path "
                f"segment in {part!r} within {argv!r}")


def render(user: str) -> str:
    """Build the sudoers file text for `user`.

    One NOPASSWD line per catalogue action with root=True, arguments
    included verbatim from `Action.argv`. Never a wildcard, never `ALL` as
    a command -- enforced here, not merely by the shape of today's
    catalogue: `user` and every element of every root action's `argv` are
    validated, and a rejection raises `ValueError` rather than emitting
    anything.
    """
    _validate_user(user)
    lines = [HEADER]
    for action in sorted(
            (a for a in CATALOGUE.values() if a.root), key=lambda a: a.id):
        _validate_argv(action.argv)
        command = " ".join(action.argv)
        lines.append(f"{user} ALL=(root) NOPASSWD: {command}")
    lines.append("")
    return "\n".join(lines)
