"""Renders the sudoers rule the console would need -- and never installs it.

The console has no code path that writes to /etc. Not one it declines to
take, not one behind a flag, not one behind a confirmation prompt: an install
mode that exists but goes unused is still an install mode someone will
eventually use. `render()` produces the file's text; `cmd_sudoers` in cli.py
writes it under packaging/, validates it with `visudo -c`, and hands the
operator the one command to run themselves.

A NOPASSWD rule is granted to a user account, not to this program. Once
installed, any process running as that account -- a script, a browser
extension, a compromised dependency -- can run the exact command below
without a password. Naming a login account here is a transitional state,
not the destination: the destination is a dedicated system user for the
service. That is why the rendered file carries the warning itself, in a
comment nobody has to go looking for a design document to find.

sudo-rs supports a subset of the classic sudoers grammar. This module stays
in the plainest possible form it accepts -- `user ALL=(root) NOPASSWD:
/absolute/path arg1 arg2` -- and uses no alias, no Defaults line, no
wildcard and never `ALL` as a command.

Both interpolated values are validated before a single line is built, and
`render()` raises rather than emit anything on a rejection:

- `user` must be a plain POSIX login name, and never the literal `ALL`.
  A username is not safe input just because it usually looks like one --
  `getpass.getuser()` (not called here; see cli.py, which resolves it from
  the password database instead) returns `$LOGNAME` / `$USER` verbatim,
  and a value such as ``prolice ALL=(ALL) NOPASSWD: ALL #`` parses
  cleanly under sudo-rs and replaces the intended rule with unrestricted
  root. The comment character swallows the rest of the line; without it,
  a bare ``ALL`` still grants every account on the machine while looking,
  at a glance, like a normal username.
- Every element of every root action's `argv` is validated against an
  **allowlist**, not a denylist. `CATALOGUE` is trusted data today, but
  this module renders whatever it is given, and a denylist of "characters
  sudoers treats specially" is a losing game: `#` opens a comment in
  sudo-rs 0.2.13 (proved against this machine's real `visudo` -- garbage
  after a bare command parses `rc=1`, the same garbage after `#` parses
  `rc=0 parsed OK`), an empty argument or a trailing `#` both degenerate
  the rule to a bare command name, which sudoers(5) documents as running
  "with any arguments they wish" -- root code execution through
  `apt-get`'s own option parsing -- and a Unicode zero-width space
  (U+200B) is invisible but is not matched by `\\s`. Only the characters
  the real catalogue's commands and arguments actually need are let
  through, `argv[0]` must be an absolute path with no `..` segment, and
  no element may be empty.
"""

from __future__ import annotations

import re

from healthconsole.actions import CATALOGUE

HEADER = """\
# Generated by `health-console sudoers`. Do not hand-edit: regenerate it
# with that command and reinstall instead.
#
# TRANSITIONAL: the rule below names a login account, not a dedicated
# system user. A NOPASSWD rule is granted to that account, not to this
# program -- any process running as it (a script, a browser extension, a
# compromised dependency) can run the exact command below without a
# password. The destination is a dedicated system user for the service;
# naming a login account here is a stepping stone, not the design.
#
# Fixed arguments only, drawn from healthconsole/actions.py -- no
# wildcard, never ALL as a command.
"""

# A plain POSIX login name: letters (either case -- POSIX allows both;
# case alone carries no meaning to sudoers), digits, underscore and
# hyphen, not starting with a digit or hyphen, at most 32 characters (the
# usual system limit). `ALL` would match this pattern -- it looks like an
# ordinary name -- which is exactly why it is rejected separately below
# rather than trusted to fall out of the character class.
_USER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_-]{0,31}")

# What an argv element is allowed to contain -- an allowlist, not a
# denylist. sudo-rs's sudoers grammar reads far more as syntax than any
# enumerated denylist catches: `#` opens a comment (mid-token, not just at
# start of line), `:` separates fields, a bare or empty trailing element
# degenerates the whole rule to just the command name -- which sudoers(5)
# documents as letting the user run it "with any arguments they wish" --
# and a Unicode zero-width space is invisible to `\s`. Only what the real
# catalogue's commands and arguments need is let through.
_ARGV_SAFE_RE = re.compile(r"[A-Za-z0-9._/-]+")


def _validate_user(user: str) -> None:
    if user == "ALL" or not _USER_RE.fullmatch(user):
        raise ValueError(
            f"refusing to render a sudoers rule for {user!r}: not a plain "
            "POSIX login name")


def _validate_argv(argv: tuple[str, ...]) -> None:
    if not argv:
        raise ValueError("refusing to render a sudoers rule: empty argv")
    if not argv[0].startswith("/"):
        raise ValueError(
            f"refusing to render a sudoers rule: argv[0] must be an "
            f"absolute path, got {argv!r}")
    if ".." in argv[0].split("/"):
        raise ValueError(
            f"refusing to render a sudoers rule: argv[0] must not contain "
            f"a '..' path segment, got {argv!r}")
    for part in argv:
        if part == "" or not _ARGV_SAFE_RE.fullmatch(part):
            raise ValueError(
                f"refusing to render a sudoers rule: unsafe argument "
                f"{part!r} in {argv!r}")


def render(user: str) -> str:
    """Build the sudoers file text for `user`.

    One NOPASSWD line per catalogue action with root=True, arguments
    included verbatim from `Action.argv`. Never a wildcard, never `ALL` as
    a command -- enforced here, not merely by the shape of today's
    catalogue: `user` and every element of every root action's `argv` are
    validated, and a rejection raises `ValueError` rather than emitting
    anything.
    """
    _validate_user(user)
    lines = [HEADER]
    for action in sorted(
            (a for a in CATALOGUE.values() if a.root), key=lambda a: a.id):
        _validate_argv(action.argv)
        command = " ".join(action.argv)
        lines.append(f"{user} ALL=(root) NOPASSWD: {command}")
    lines.append("")
    return "\n".join(lines)
